- name: Fail if required parameters are missing
  fail:
    msg: "Missing required parameters for backup: database_type, name_backup, or aws_dest"
  when: item.database_type is not defined or item.name_backup is not defined or item.aws_dest is not defined
  with_items: "{{ backups }}"

- name: Configure cron tasks
  cron:
    name: "Backup {{ item.name_backup }}"
    minute: "{{ item.cron.minute }}"
    hour: "{{ item.cron.hour }}"
    day: "{{ item.cron.day }}"
    weekday: "{{ item.cron.weekday }}"
    month: "{{ item.cron.month }}"
    job: |
      /usr/local/bin/backup_universal/backup.py -t {{ item.database_type }} -n {{ item.name_backup }} -d {{ item.aws_dest }} -u {{ item.database_user }} -p {{ item.database_password }} -H {{ item.database_host }} -P {{ item.database_port }} {% if item.retain_count is defined %}-r {{ item.retain_count }}{% endif %} {% if item.exp_date is defined and item.exp_date|length > 0 %}-e {{ item.exp_date }}{% endif %} {% if item.container_name is defined %}--container_name {{ item.container_name }}{% endif %} {% if item.aws_endpoint is defined %}--aws_endpoint {{ item.aws_endpoint }}{% endif %} {% if item.tmp_dir is defined %}--tmp_dir {{ item.tmp_dir }}{% endif %} >> /var/log/backup_universal.log 2>&1
  with_items: "{{ backups }}"
