- name: Configure cron tasks
  cron:
    name: "Backup {{ item.name_backup }}"
    minute: "{{ item.cron.minute }}"
    hour: "{{ item.cron.hour }}"
    day: "{{ item.cron.day }}"
    weekday: "{{ item.cron.weekday }}"
    month: "{{ item.cron.month }}"
    job: |
      /usr/local/bin/backup_universal/backup.py -t {{ item.database_type }} -n {{ item.name_backup }} -d {{ item.aws_dest }} -u {{ item.database_user }} -p {{ item.database_password }} -h {{ item.database_host }} -P {{ item.database_port }} -r {{ item.retain_count }} -e {{ item.exp_date }} >> /var/log/backup_universal.log 2>&1
  with_items: "{{ backup.databases }}"
