- name: Ensure backup directory exists
  file:
    path: "/etc/backup"
    state: directory
    mode: "700"

- name: Ensure temporary directory exists
  file:
    path: "{{ item.tmp_dir }}"
    state: directory
    mode: "700"
  with_items: "{{ backups }}"

- name: Create backup directory
  file:
    path: "/etc/backup"
    state: directory
    mode: "700"

- name: Create AWS credentials file
  template:
    src: credentials.j2
    dest: "/usr/local/bin/backup_universal/credentials_{{ item.name_backup }}"
    mode: "600"
  with_items: "{{ backups }}"

- name: Create Apprise config files
  template:
    src: apprise_config.j2
    dest: "/etc/backup/apprise_config_{{ item.name_backup }}"
    mode: "600"
  with_items: "{{ backups }}"
  when: item.notifications.enabled | default(false)

- name: Delete Apprise config files when notifications are disabled
  file:
    path: "/etc/backup/apprise_config_{{ item.name_backup }}"
    state: absent
  with_items: "{{ backups }}"
  when: not item.notifications.enabled | default(false)
