- name: Create backup directory
  file:
    path: "/etc/backup"
    state: directory
    mode: "700"

- name: Create AWS credentials file
  template:
    src: credentials.j2
    dest: "/etc/backup/credentials"
    mode: "600"

- name: Create Apprise config file
  template:
    src: apprise_config.j2
    dest: "{{ backup.apprise_config }}"
    mode: "600"
  when: backup.notifications.enabled

- name: Delete Apprise config when notifications are disabled
  file:
    path: "{{ backup.apprise_config }}"
    state: absent
  when: not backup.notifications.enabled
