- name: Create backup directory
  file:
    path: "/etc/backup"
    state: directory
    mode: "700"

- name: Create AWS credentials file
  template:
    src: credentials.j2
    dest: "/etc/backup/credentials"
    mode: "600"

- name: Create Apprise config file
  template:
    src: apprise_config.j2
    dest: "{{ backup.apprise_config }}"
    mode: "600"
  when: backup.notifications.enabled

- name: Create a config dir
  file:
    path: "/usr/local/bin/{{ item.database_type }}"
    state: directory
    mode: "600"
  with_items: "{{ backup.databases }}"

- name: Copy backup executable file
  template:
    src: "{{ item.database_type }}.j2"
    dest: /usr/local/bin/{{ item.database_type }}/backup.sh
    mode: "700"
  with_items: "{{ backup.databases }}"

- name: Copy backup apprise config
  template:
    src: "apprise_config.j2"
    dest: /etc/backup/apprise_config
    mode: "600"
  when: backup.notifications.enabled and backup.notifications.apprise_target != ""

- name: Delete apprise_config when notification is turned off
  file:
    path: /etc/backup/apprise_config
    state: absent
  when: not backup.notifications.enabled or backup.notifications.apprise_target == ""