- name: Install required packages
  package:
    name:
      - python3
      - python3-pip
      - awscli
      - postgresql-client
      - mysql-client
      - mongodb-clients
    state: present
  become: yes

- name: Install Python libraries
  pip:
    name:
      - boto3
      - apprise
    state: present
  become: yes
