- name: Install required packages
  package:
    name:
      - python3
      - python3-pip
      - awscli
    state: present
  become: yes

- name: Install Python libraries
  pip:
    name:
      - boto3
      - apprise
    state: present
  become: yes

- name: Check to postgresql-client-common
  package:
    name: postgresql-client-common
    state: present
- name: Check to postgresql-client-common
  package:
    name: postgresql-client
    state: present
