- name: Install dependencies
  include_tasks: install_dependencies.yml
  tags: install

- name: Create configs
  include_tasks: create_configs.yml
  tags: config

- name: Ensure backup script directory exists
  file:
    path: /usr/local/bin/backup_universal
    state: directory
    mode: "0755"
  tags: script

- name: Copy backup script to target host
  copy:
    src: ../scripts/backup.py
    dest: /usr/local/bin/backup_universal/backup.py
    mode: "0755"
  tags: script

- name: Configure cron jobs
  include_tasks: configure_cron.yml
  tags: cron
