- name: Install dependencies
  include_tasks: install_dependencies.yml
  tags: install

- name: Create configs
  include_tasks: create_configs.yml
  tags: config

- name: Run backup script
  command: >
    python3 /home/jony/personal/repos/github/backup_universal/scripts/backup.py
  tags: backup
